# Generated by Django 5.2.7 on 2025-11-18 14:52

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('BLOCAGE', 'Blocage'), ('DECISION', 'Décision'), ('ACTION', 'Action requise')], default='INFO', max_length=8)),
                ('contenu', models.TextField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(blank=True, max_length=124, null=True)),
                ('url', models.URLField()),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=124, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, help_text='Liens vers la GED', related_name='%(class)s_documents', to='workload.document')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue de début')),
                ('end_date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue de fin')),
                ('start_date_reel', models.DateField(blank=True, null=True, verbose_name='Date réelle de début')),
                ('end_date_reel', models.DateField(blank=True, null=True, verbose_name='Date réelle de fin')),
                ('nom', models.CharField(max_length=124, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PLANNED', 'Planifié'), ('ACTIVE', 'En cours'), ('ON_HOLD', 'En pause'), ('DONE', 'Terminé'), ('CANCELED', 'Annulé')], default='PLANNED', max_length=16)),
                ('priorite', models.IntegerField(choices=[(1, 'Basse'), (2, 'Moyenne'), (3, 'Haute')], default=2)),
                ('percent_complete', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Progression (%)')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, help_text='Liens vers la GED', related_name='%(class)s_documents', to='workload.document')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projets', to='workload.mission')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('r1', models.ForeignKey(help_text='Responsable du projet', on_delete=django.db.models.deletion.PROTECT, related_name='projets_coordonnes', to=settings.AUTH_USER_MODEL, verbose_name='Coordinateur')),
                ('r2', models.ForeignKey(blank=True, help_text='Remplaçant du coordinateur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_backup', to=settings.AUTH_USER_MODEL, verbose_name='BackUp')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Livrable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue de début')),
                ('end_date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue de fin')),
                ('start_date_reel', models.DateField(blank=True, null=True, verbose_name='Date réelle de début')),
                ('end_date_reel', models.DateField(blank=True, null=True, verbose_name='Date réelle de fin')),
                ('nom', models.CharField(max_length=124, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('DUE', 'Échu'), ('SUBMITTED', 'Soumis'), ('APPROVED', 'Validé'), ('REJECTED', 'Rejeté')], default='PLANNED', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('depends_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_dependants', to='workload.livrable', verbose_name='Dépend de')),
                ('documents', models.ManyToManyField(blank=True, help_text='Liens vers la GED', related_name='%(class)s_documents', to='workload.document')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='livrables_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du livrable')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livrables', to='workload.projet', verbose_name='Projet parent')),
            ],
            options={
                'ordering': ['end_date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=124, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('complete', models.BooleanField(default=False, verbose_name='La tâche est-elle terminée ?')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, help_text='Liens vers la GED', related_name='%(class)s_documents', to='workload.document')),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='taches_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable de la tâche')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Implication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start_date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue de début')),
                ('end_date_prevue', models.DateField(blank=True, null=True, verbose_name='Date prévue de fin')),
                ('start_date_reel', models.DateField(blank=True, null=True, verbose_name='Date réelle de début')),
                ('end_date_reel', models.DateField(blank=True, null=True, verbose_name='Date réelle de fin')),
                ('object_id', models.PositiveIntegerField()),
                ('nature', models.IntegerField(choices=[(1, 'Ponctuelle'), (2, 'Récurrente'), (3, 'Continue')], default=3)),
                ('contribution', models.PositiveSmallIntegerField(default=0, help_text="Implication de l'Agent (%)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('role', models.CharField(blank=True, max_length=124, verbose_name='Rôle dans le projet')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'agent'), name='implication_unique')],
            },
        ),
    ]
