# Generated by Django 5.2.7 on 2025-11-28 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implication',
            name='contribution',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='implication',
            name='role',
            field=models.CharField(blank=True, max_length=124, verbose_name='Rôle'),
        ),
    ]
