# Generated by Django 5.2.7 on 2025-11-19 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_tache_mission_tache_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='responsable',
        ),
    ]
