# Generated by Django 5.2.7 on 2025-11-28 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_alter_implication_contribution_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='r1',
            field=models.ForeignKey(blank=True, help_text='Responsable du projet', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projets_coordonnes', to=settings.AUTH_USER_MODEL, verbose_name='Coordinateur'),
        ),
    ]
