# Generated by Django 5.2.7 on 2025-11-28 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_alter_projet_r1'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrable',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livrables_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du livrable'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='r1',
            field=models.ForeignKey(blank=True, help_text='Responsable du projet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_coordonnes', to=settings.AUTH_USER_MODEL, verbose_name='Coordinateur'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='r2',
            field=models.ForeignKey(blank=True, help_text='Remplaçant du coordinateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_backup', to=settings.AUTH_USER_MODEL, verbose_name='BackUp'),
        ),
    ]
